### ISSUE TITLE
chaining processContent 

### ISSUE THREAD

**Issue by HassenPy** [auremoser/sg-events#9]
Hi,
i'm working on adding some feature requested here https://github.com/mozillascience/studyGroupEvents/issues/5

Got stuck trying to chain a function after all the `processContent` functions resolve, so i tried making the function return a promise so i can push all instances to an array and use `Bluebird.all()` on them, but it seems like this isn't working too.

The function after changes:
```
function processContent(forks){
  // Just made it return a promise
  return new Bluebird(function(resolve, reject){
    forks.map(function(fork){
      var repo = octo.repos(fork.user, fork.repo);
      var filepath = require('path').resolve('./data/'+ fork.user);
      mkdirp.sync(filepath);

      // `.fetch` is used for getting JSON
      repo.contents('_posts').fetch().then(function(contents) {

        var promises = [];
        contents.map(function(file){
          promises.push(repo.contents(file.path).read());
        });

        var file = [];
        Bluebird.all(promises).then(function(files){
          files.map(function(contents){
            file.push(matter(contents).data);
            appendEvent(matter(contents).data);
          });
          require('fs').writeFileSync(filepath + '/data.json', JSON.stringify(file, null, 4), 'utf-8');
          resolve('resolved');
        }).catch(function(err){
          console.error('Batch create file error');
          console.error('ERROR: %s.\n%s', err.message, err.stack);
          reject('Batch create file error');
        });
      }).catch(function(err){
        console.error('Fetch repo _posts error');
        console.error('ERROR: %s.\n%s', err.message, err.stack);
      });
    });
  });
}
```

The chaining i'm trying to get to work, i just made the script push all `processContent` functions to an array to be able to wait for all of them to resolve with `Bluebird.all()`:
```
var processingPromises = [];
Bluebird.all(promises).then(function(batches){
    batches.map(function(batch){
        // Push to an array
        processingPromises.push(processContent(batch));
     });
     Bluebird.all(processingPromises).then(function(){
          // ---> This doesn't seem to fire <---
          pushEvents();
     });
}).catch(function(err){
    console.error('Batch download error');
    console.error('ERROR: %s.\n%s', err.message, err.stack);
});
```

**Comment by AnamikaD** [comment]
@HassenPy nice job!!! @auremoser Please review this!!

**Comment by HassenPy** [comment]
just got back to this and found why that wasn't firing, it was because the promise .all() fails even if a single promise fails, i knew this info but i just got lost in the nested promises, finally ...  :v:

**Comment by auremoser** [comment]
Promises, promises! I'm glad you figured it out and I'm sorry it was taking me forever to give you feedback!

How is it going now @HassenPy ?

**Comment by HassenPy** [comment]
np really, this was an opportunity for me to learn more about the ECMAScript world while doing something useful instead of a dummy project. :ok_hand: 

gonna do a little cleanup when i have time then a PR.

**Comment by AnamikaD** [comment]
@HassenPy amazing job! I would like to learn this from you :D :)

**Comment by HassenPy** [comment]
will send you the links that helped me while solving this :)
